---
loggers:
  system_logger:
    handlers:
    - console_handler
    - file_handler
    propagate: false
    level: INFO
  trace_logger:
    handlers:
      - console_handler
      - file_handler
    propagate: false
    level: INFO
version: 1
root:
  handlers:
  - console_handler
  level: INFO
handlers:
  console_handler:
    formatter: console_simple_formatter
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file_handler:
    backupCount: 30
    encoding: utf-8
    filename: "/tmp/system.log"
    formatter: file_json_formatter
    class: logging.handlers.RotatingFileHandler
    maxBytes: 15728640
formatters:
  file_json_formatter:
    "()": fl.logging_utils.logger_formatter.BaseJsonFormatter
    json_ensure_ascii: false
    timestamp: true
    format: "%(created)f %(msecs)d %(relativeCreated)d %(levelname)s %(name)s %(asctime)s
      %(module)s  %(message)s"
  console_simple_formatter:
    format: "[%(levelname)s] %(name)s %(asctime)s %(module)s: %(message)s"